### ISSUE TITLE
Networking outside of operations

### ISSUE THREAD

**Issue by wibosco** [GabrielMassana/CocoaPods-Search#3]
I was thinking about the networking arch of this project and if we should go down the path of having our networking requests inside NSOperation subclasses - i think that because this app doesn't require a user account that we could go with networking calls outside of NSOperation (using nsurlsession's built multi-threading support) and leave the NSOepration to handle the parsing of the data returned?

@GabrielMassana  What do you think?

**Comment by GabrielMassana** [comment]
For me it is ok to do things in different ways. I think @lagubull will be happy too.
That means we need a new Networking pod?

**Comment by GabrielMassana** [comment]
So I tweaked a little bit the pod (one line to be more clear) and I'm calling the API without operation.

I created a PR with it, I think is what you were saying.
